const express=require('express')
const { CreateProduct, GetAllProducts, UpdateProductbyId, DeleteProductbyId, FetchproductbyId, CreateUser, loginuser, addToCart, fetchCart, DeleteFromCart, UpdateFromCart, liked, fetchliked, DeleteFromliked, Makenewadmin, CreateOrder, fetchorder, DeleteAllFromCart, updateorder, OrderStatus, deleteorder } = require('../controller/product')
const isauthenticated = require('../Middleware/middleware')
const route=express.Router()
route.post('/Product/Add',isauthenticated,CreateProduct)
route.get('/products/display',GetAllProducts)
route.put('/product/update/:id', UpdateProductbyId);
route.delete('/product/delete/:id',DeleteProductbyId)
route.get('/product/overview/:id',FetchproductbyId)
route.post('/Create/user',CreateUser)
route.post('/login/user',loginuser)
route.post('/product/addtocart/:id',isauthenticated,addToCart)
route.get('/product/cart/items',isauthenticated,fetchCart)
route.delete('/product/cart/delete/:id',isauthenticated,DeleteFromCart)
route.put('/product/cart/update/:id',isauthenticated,UpdateFromCart)
route.post('/product/favorite/:id',isauthenticated,liked)
route.get('/product/favorite/display',isauthenticated,fetchliked)
route.delete('/product/favourite/delete/:id',isauthenticated,DeleteFromliked)
route.post('/Admin/New/admin',isauthenticated,Makenewadmin)
route.post('/product/order',isauthenticated,CreateOrder)
route.get('/orders/list',isauthenticated,fetchorder)
route.delete('/product/cart/delete',isauthenticated,DeleteAllFromCart)
route.put('/Admin/Orders/view/:id/product/:productId', isauthenticated, updateorder);
route.get('/user/orders',isauthenticated,OrderStatus)
route.delete('/order/delete/:id/product/:productid',isauthenticated,deleteorder)
module.exports=route